name: Rodar Código de Notícias e Telegram (Run Bot)

on:
  push:
    branches:
      - main # Isso faz o código rodar sempre que você enviar uma atualização para o "main" (ramo principal)

jobs:
  build:
    runs-on: ubuntu-latest # Vai rodar no servidor do GitHub

    steps:
      - name: Fazer o check-out do código (Checkout repository)
        uses: actions/checkout@v2

      - name: Configurar Python (Set up Python)
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Vai instalar as bibliotecas necessárias do seu código

      - name: Rodar o script Python (Run Bot)
        run: |
          #python seu_script.py  # Altere "seu_script.py" para o nome do seu arquivo Python
          python main.py
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY_SECRET }} # Aqui, você passa a chave secreta do Telegram
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_SECRET }} # Aqui, você passa a chave secreta das notícias

